const BagActionTypes = {
    GENERATE_BAG_START: ' GENERATE_BAG_START',
    GENERATE_BAG_SUCCESS: ' GENERATE_BAG_SUCCESS',
    GENERATE_BAG_FAILURE: 'GENERATE_BAG_FAILURE',
    GET_NUMOFBAGS_START: 'GET_NUMOFBAGS_START',
    GET_NUMOFBAGS_SUCCESS: 'GET_NUMOFBAGS_SUCCESS',
    GET_NUMOFBAGS_FAILURE: ' GET_NUMOFBAGS_FAILURE',

    LINK_BAG_START: 'LINK_BAG_START',
    LINK_BAG_SUCCESS: 'LINK_BAG_SUCCESS',
    LINK_BAG_FAILURE: ' LINK_BAG_FAILURE',
    // GET_BAGS_START: 'GET_BAGS_START',
    // GET_BAGS_SUCCESS: 'GET_BAGS_SUCCESS',
    // GET_BAGS_FAILURE: 'GET_BAGS_FAILURE',
  };
  
  export default BagActionTypes;
  